### ISSUE TITLE
wifi todo

### ISSUE THREAD

**Issue by seanpringle** [seanpringle/factropy#40]
* [ ] rename signals to packets?
* [ ] showing all network SSIDs in networker connection drop-down gets confusing
  * just those in range? toggle between in-range and all? 
* [ ] hover overlay uses colored lines to show local and wide area network links
  * change to an animated, translucent packet stream? use a modified particle emitter?
